baseurl = "https://dhayalan.com/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Siva Dhayalan"
title = "Siva Dhayalan"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Documenting myself"
# copyright = ""
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
#logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
share = false
# Share to googleplus, twitter, fb, linkedin by default
# disable by setting share_on_<social network> = false
# example: share_on_googleplus = false
#latestpostcount = false
github = "dsivasuthan"
email = "you@example.com"
linkedin = "dsivasuthan"
twitter = false
facebook = false
instagram = "sdhayalan"
itch_io = false
#social_banner = false
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
# githubRepo = "githubUsername/repositoryName/tree/master"
small_banner_logo = false
align_left = true

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"
